// Generated by scripts/build-sw.mjs. Do not edit by hand.
const CACHE = 'guo-games-mudt7bkv';
const SHELL = [
  "/guo-games/",
  "/guo-games/index.html",
  "/guo-games/manifest.webmanifest",
  "/guo-games/icon.svg",
  "/guo-games/icon-192.png",
  "/guo-games/icon-512.png",
  "/guo-games/fonts/fraunces.ttf",
  "/guo-games/assets/index-DOscMmjd.js",
  "/guo-games/assets/index-Dl564092.css"
];

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      // Only this app's own old shells, including the first build's
      // guo-games-shell-v1. Another app on the same origin keeps its caches.
      .then((keys) =>
        Promise.all(keys.filter((key) => key.startsWith('guo-games-') && key !== CACHE).map((key) => caches.delete(key))),
      )
      .then(() => self.clients.claim()),
  );
});

// Cache first for the shell, network for anything else. The app has no API, so
// a cache hit is always correct and the whole day works with no signal.
//
// ignoreVary matters: a server that answers with "Vary: Origin" makes the
// module script request (which carries an Origin header) miss the entry that
// install cached without one, and the app then opens offline as a blank page.
// Every shell URL is content-hashed or tiny, so ignoring Vary is safe here.
// Lookups go to this build's cache only, so no older or unrelated cache on the
// origin can answer with a stale index.html.
const lookup = (request) => caches.open(CACHE).then((cache) => cache.match(request, { ignoreVary: true }));

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    lookup(event.request).then((hit) => {
      if (hit) return hit;
      return fetch(event.request)
        .then((response) => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(event.request, copy));
          }
          return response;
        })
        .catch(() => {
          // Only a page navigation can sensibly fall back to the app shell.
          // Handing index.html to an <img> or an <audio> just fails oddly.
          if (event.request.mode === 'navigate') return lookup('/guo-games/index.html');
          return Response.error();
        });
    }),
  );
});
