/**
 * Writes the service worker after a build, with the real hashed asset names
 * baked in. Generating it here means the offline shell can never drift from
 * what Vite actually emitted.
 */
import { readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

// fileURLToPath, not URL.pathname: pathname keeps percent-encoding, so a
// checkout under a path with a space resolved to a directory that is not there.
const dist = fileURLToPath(new URL('../dist/', import.meta.url));
// The same base Vite built with, so a /guo-games/ build caches /guo-games/ URLs.
const base = process.env.GUO_BASE ?? '/';
const assets = readdirSync(join(dist, 'assets')).map((name) => `assets/${name}`);
const shell = ['', 'index.html', 'manifest.webmanifest', 'icon.svg', 'icon-192.png', 'icon-512.png', 'fonts/fraunces.ttf', ...assets].map(
  (path) => `${base}${path}`,
);
const version = `guo-games-${Date.now().toString(36)}`;

writeFileSync(
  join(dist, 'sw.js'),
  `// Generated by scripts/build-sw.mjs. Do not edit by hand.
const CACHE = '${version}';
const SHELL = ${JSON.stringify(shell, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(SHELL)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      // Only this app's own old shells, including the first build's
      // guo-games-shell-v1. Another app on the same origin keeps its caches.
      .then((keys) =>
        Promise.all(keys.filter((key) => key.startsWith('guo-games-') && key !== CACHE).map((key) => caches.delete(key))),
      )
      .then(() => self.clients.claim()),
  );
});

// Cache first for the shell, network for anything else. The app has no API, so
// a cache hit is always correct and the whole day works with no signal.
//
// ignoreVary matters: a server that answers with "Vary: Origin" makes the
// module script request (which carries an Origin header) miss the entry that
// install cached without one, and the app then opens offline as a blank page.
// Every shell URL is content-hashed or tiny, so ignoring Vary is safe here.
// Lookups go to this build's cache only, so no older or unrelated cache on the
// origin can answer with a stale index.html.
const lookup = (request) => caches.open(CACHE).then((cache) => cache.match(request, { ignoreVary: true }));

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    lookup(event.request).then((hit) => {
      if (hit) return hit;
      return fetch(event.request)
        .then((response) => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(event.request, copy));
          }
          return response;
        })
        .catch(() => {
          // Only a page navigation can sensibly fall back to the app shell.
          // Handing index.html to an <img> or an <audio> just fails oddly.
          if (event.request.mode === 'navigate') return lookup('${base}index.html');
          return Response.error();
        });
    }),
  );
});
`,
  'utf8',
);

console.log(`sw.js written with ${shell.length} shell entries`);
