import { describe, expect, it } from 'vitest';
import { act, join, load, save, seed, scores, STORAGE_KEY, validateMedia, vaultEntries, visibleScores, privateMission, futureEntries, EXPIRES_AT, isRecap } from './game';
const NOW = Date.parse('2027-05-01T18:00:00Z');
const kevin = () => join(seed(), 'GUO27', 'Kevin', 'Kevin', 'sea');
describe('Guo Games core', () => {
 it('joins roster identities and spectators with the party code', () => { expect(join(seed(),' guo27 ','Kevin','Kev','coral').session).toEqual({attendee:'Kevin',name:'Kev',color:'coral'}); expect(join(seed(),'GUO27','Spectator','Guest','sea').session?.attendee).toBe('Spectator'); expect(()=>join(seed(),'BAD','Kevin','Kev','sea')).toThrow('party code'); });
 it('caps predictions, settles by organizers, and voids without penalty', () => { let s=kevin(); s=act(s,{type:'pick',id:'flight',choice:'yes'},NOW); s=act(s,{type:'pick',id:'fishing',choice:'no'},NOW); s=act(s,{type:'pick',id:'downtime',choice:'yes'},NOW); expect(()=>act(s,{type:'pick',id:'dinner',choice:'yes'},NOW)).toThrow('three'); s=join(s,'GUO27','Deniz','Deniz','sea'); s=act(s,{type:'settle',id:'flight',result:'yes'},NOW); expect(scores(s).find(x=>x.attendee==='Kevin')?.points).toBe(10); s=act(s,{type:'voidPrediction',id:'flight'},NOW); expect(scores(s).find(x=>x.attendee==='Kevin')?.points).toBe(0); });
 it('prevents duplicate fish drafts and releases changed draft species', () => { let s=act(kevin(),{type:'draft',fish:'Mahi-mahi'},NOW); s=join(s,'GUO27','Nick','Nick','sea'); expect(()=>act(s,{type:'draft',fish:'Mahi-mahi'},NOW)).toThrow('drafted'); s=act(s,{type:'draft',fish:'Ono'},NOW); s=act(s,{type:'draft',fish:'Ahi'},NOW); s=join(s,'GUO27','Nate','Nate','sea'); expect(act(s,{type:'draft',fish:'Ono'},NOW).draft.Nate).toBe('Ono'); });
 it('requires opt-in bounty and different witness', () => { let s=kevin(); expect(()=>act(s,{type:'confirm',id:'callback'},NOW)).toThrow('claim'); s=act(s,{type:'claim',id:'callback'},NOW); expect(()=>act(s,{type:'confirm',id:'callback'},NOW)).toThrow('different'); s=join(s,'GUO27','Nick','Nick','sea'); s=act(s,{type:'confirm',id:'callback'},NOW); expect(s.bounties.callback.witness).toBe('Nick'); });
 it('handles missions privately and safely', () => { let s=kevin(); expect(privateMission(s)?.text).toContain('thank'); expect(privateMission(join(s,'GUO27','Spectator','Guest','sea'))).toBeNull(); expect(()=>act(s,{type:'mission',status:'done'},NOW)).toThrow('accept'); s=act(s,{type:'mission',status:'accepted'},NOW); expect(act(s,{type:'mission',status:'done'},NOW).missions.Kevin).toBe('done'); });
 it('validates vault media and reveal/remove permissions', () => { expect(()=>validateMedia({name:'x.svg',type:'image/svg+xml',bytes:1,data:'data:image/svg+xml;base64,AA=='})).toThrow('JPEG'); let s=act(kevin(),{type:'submitMemory',about:'Kevin',moment:'Dinner',text:'A kind story',media:null},NOW); const id=s.vault[0].id; expect(vaultEntries(join(s,'GUO27','Jack','Jack','sea'))).toHaveLength(0); s=join(s,'GUO27','Deniz','Deniz','sea'); s=act(s,{type:'dinner'},NOW); s=act(s,{type:'revealMemory',id},NOW); expect(vaultEntries(join(s,'GUO27','Jack','Jack','sea'))).toHaveLength(1); expect(act(join(s,'GUO27','Kevin','Kevin','sea'),{type:'removeMemory',id},NOW).vault).toHaveLength(0); });
 it('reveals dinner awards and keeps future sealed', () => { let s=act(kevin(),{type:'sealFuture',text:'Still friends.'},NOW); expect(futureEntries(s,NOW)).toEqual([]); expect(visibleScores(s)).toBeNull(); s=join(s,'GUO27','Nick','Nick','sea'); s=act(s,{type:'settings',hideRankings:false,awards:'points'},NOW); expect(visibleScores(s)).toHaveLength(7); });
 it('enforces date kill switch for mutations but allows joining recap', () => { const deadline=Date.parse(EXPIRES_AT); expect(isRecap(deadline-1)).toBe(false); expect(isRecap(deadline)).toBe(true); const s=join(seed(),'GUO27','Deniz','Deniz','sea'); expect(()=>act(s,{type:'draft',fish:'Ono'},deadline)).toThrow('read-only'); expect(join(s,'GUO27','Kevin','Kev','coral').session?.attendee).toBe('Kevin'); });
 it('persists, migrates defaults, and rejects corrupt data', () => { const values=new Map<string,string>(); const storage={getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>values.set(k,v)}; expect(load(storage).session).toBeNull(); const s=act(kevin(),{type:'draft',fish:'Ono'},NOW); save(storage,s); expect(load(storage)).toEqual(s); storage.setItem(STORAGE_KEY,JSON.stringify({version:1,session:s.session,draft:s.draft})); expect(load(storage).settings).toEqual({hideRankings:true,awards:'stories'}); storage.setItem(STORAGE_KEY,'broken'); expect(()=>load(storage)).toThrow('saved'); });
});
